sources:
  - Russolo.glyphs
axisOrder:
  - opsz
  - wght
buildVariable: true
buildStatic: true
buildWebfont: false
ttDir: "../fonts/ttf"
ttDir: "../fonts/otf"
vfDir: "../fonts/variable"
familyName: Russolo
stat:
  - name: Optical Size
    tag: opsz
    values:
    - name: 10pt
      value: 10
      flags: 2
    - name: 24pt
      value: 24
    - name: 72pt
      value: 72
  - name: Weight
    tag: wght
    values:
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
